### ISSUE TITLE
Beberapa yang bisa kamu improve 

### ISSUE THREAD

**Issue by k-ardliyan** [naufalf25/Interactive-Rating-Component#1]
Mungkin dari aku ya @naufalf25 

- [x] Style dari radio buttonnya kurang full width ke pembungkusnya si `class="rating-num"` jadi yang nomer lima kurang mojok kekanan, kalau bisa di perfectkan hehe.
- [x] Kalau boleh si pembungkus `<input>` itu jangan `<label>`, karena `<label>` itu biasanya bersamaan sama `<input>`, jadi bisa bungkus pakai `<div>`. cuma karena biar bisa diklik full gak masalah deng

- [x] Lalu kondisi user mau submit rating kalau bisa si user kalau gak memberi rating keluarkan alert, kalau ngisi baru pindah tampilan berikutnya, karena untuk saat ini tanpa memberi ratingpun bisa berubah tampilannya.
```js
var rate_check = document.querySelector("input[name='rate']:checked");
if (rate_check) {
    var rate_value = rate_check.value;
    insertCss(
        ".rating-section {display: none;}" +
        ".thankyou-section {display: unset}"
    )
} else {
    rate_value = alert("Please select a rating");
}
```

begitulah saran dariku, nanti kalau udah di fix bisa di centang-centang wkwk

**Comment by naufalf25** [comment]
Oke makasih masukannya mas @k-ardliyan 

Semua task alhamdulillah sudah bisa semua. Cuma masih jadi catatanku ini mas, 
1. Poin 1 ini style dari `class="rating-num"` ini antara akunya kurang jeli atau gimana, tapi ndak nemu masalahnya ini kok kayak ada `margin-right`. Akhirnya tak akalin dengan pake `margin-right: -10px`, mungkin kedepannya bakal coba tak cari lagi permasalahannya.
2. Poin 2 ini tak anggap aman dulu yak mas hihi, karena aku juga ngikut beberapa referensi nyontohi kaya gitu juga.
3. Poin 3 ini aku coba utek-utek sendiri lagi bisa mas, dengan nambahi `.innerHTML` saat tidak memilih rating. Yang tadi muter-muter itu disini, udah coba pake `alert()` tapi hasilnya walaupun udah milih rating tetep ae itu alert keluar. Akhirnya tak akalin pake cara itu tambahi `.innerHTML`.

Mungkin itu aja sih mas, makasih banyak masukannya hehe. Ini juga sambil kuliah, nyambi belajar web 😄 
Next rencana sih coba kelarin semua project di frontendmentor.io 😆

**Comment by k-ardliyan** [comment]
Nice @naufalf25 sudah mantap, aku juga nyoba buat, pengen ikutan juga jadinya wkwkw, kalau misal pengen nonton mangga. [Go to Repository](https://github.com/k-ardliyan/interactive-rating-component)

**Comment by naufalf25** [comment]
Mantap mas @k-ardliyan, lebih bagus tampilanne dari punyaku 👍 😆
